### ISSUE TITLE
govspeak markdown file fails to output when no chart chunk is provided

### ISSUE THREAD

**Issue by crisrengifo** [Defra-Data-Science-Centre-of-Excellence/rgovspeak#2]
When knitting a rmd without any chart chunks the HTML file outputs correctly but fails to convert to md file into the govspeak format.

**Comment by clarebetts-code** [comment]
is there an update to this issue? we are having the same problem.

**Comment by crisrengifo** [comment]
Hi Clare, I've not looked at this since I opened it but an interim solution I used to was to add a dummy chart at the bottom of the markdown and then delete the chart reference at the bottom before sending it off for publication.

Not ideal but worked for me when I needed it,

**Comment by mormyrid1** [comment]
Fixed in latest release.
