### ISSUE TITLE
Unable to output to a different folder

### ISSUE THREAD

**Issue by cat-hand** [Defra-Data-Science-Centre-of-Excellence/rgovspeak#3]
I want to be able to save outputs to a different folder with a custom name - the documentation for render() suggests that setting the new output folder in knitr::opts_knit$set(root.dir = ...) should do this, but it doesn't work. It would be good if there was an argument in the govspeak function that would allow saving to a different location with a custom folder name (i.e. not being tied to the outout folder being called 'output').

**Comment by mormyrid1** [comment]
Fixed in latest release.
